import Navbar from "@/components/Navbar";
import { Anonymous_Pro, DM_Mono, DM_Sans } from "next/font/google";

import "./globals.css";

const inter = Anonymous_Pro({ weight: ["400", "700"], subsets: ["latin"] });
// Import DM Sans and DM Mono from next/font/google

// Configure DM Sans
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Define the font weights you want
  display: "swap",
});

// Configure DM Mono
const dmMono = DM_Mono({
  subsets: ["latin"],
  weight: ["400", "500"], // Define the font weights you want
  display: "swap",
});
export const metadata = {
  title: "juice",
  description: "Generated by juice",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${dmSans.variable} ${dmMono.variable}`}>
      <body className={inter.className}>
        <Navbar />
        <div className="px-6 mb-20">{children}</div>
      </body>
    </html>
  );
}
